### ISSUE TITLE
Tutorials exit with errors

### ISSUE THREAD

**Issue by AQ18** [EPFL-LCSB/skimpy#8]
In an unmodified installation of SKiMpy, every tutorial script exits with error when run in the way described in the Docker README, except for `python /skimpy/tutorials/basics/tutorial_import_cobra.py`.

Full tracebacks are available [here](https://controlc.com/dfb4ce13). There are a few unique error messages and a couple recurring themes:
```
FileNotFoundError: [Errno 2] No such file or directory: 'output/****.html'
```
```
cobra.exceptions.SolverNotFound: optlang-cplex is not a valid solver interface. Pick from ['glpk_exact', 'glpk', 'scipy'].
```

The spread of the problem makes me suspect that something is still broken in my installation even after the fixes in #7.

**Comment by weilandtd** [comment]
I think everything is alright with your installation. I am currently in the review process of the paper and "fixing" the tutorials is part of it.  

> `FileNotFoundError: [Errno 2] No such file or directory: 'output/****.html'`

You need to make the "output" folder yourself currently as empty folders are not taken into account in the git tree. This will soon be fixed.

> `cobra.exceptions.SolverNotFound: optlang-cplex is not a valid solver interface. Pick from ['glpk_exact', 'glpk', 'scipy'].`

This is due to the fact that the default LP/MILP solvers in the models we put up as examples is [cplex](https://www.ibm.com/analytics/cplex-optimizer). I will take care of this also and come back to you. 

It should be generally said that if you want to work with large-scale kinetic models and you want to use the ORACLE parametrization pipeline (see papers below). I strongly recommend to install a commercially available solver that is compatible with [pytfa](https://github.com/EPFL-LCSB/pytfa).

Wang, L.; Birol, I.; Hatzimanikatis, V. Metabolic Control Analysis under Uncertainty: Framework Development and Case Studies. Biophys J 2004, 87 (6), 3750–3763. https://doi.org/10.1529/biophysj.104.048090.
Miskovic, L.; Hatzimanikatis, V. Production of Biofuels and Biochemicals: In Need of an ORACLE. Trends in Biotechnology 2010, 28 (8), 391–397. https://doi.org/10.1016/j.tibtech.2010.05.003.
Chakrabarti, A.; Miskovic, L.; Soh, K. C.; Hatzimanikatis, V. Towards Kinetic Modeling of Genome-Scale Metabolic Networks without Sacrificing Stoichiometric, Thermodynamic and Physiological Constraints. Biotechnol J 2013, 8 (9), 1043–1057. https://doi.org/10.1002/biot.201300091.
Savoglidis, G.; da Silveira Dos Santos, A. X.; Riezman, I.; Angelino, P.; Riezman, H.; Hatzimanikatis, V. A Method for Analysis and Design of Metabolism Using Metabolomics Data and Kinetic Models: Application on Lipidomics Using a Novel Kinetic Model of Sphingolipid Metabolism. Metab Eng 2016, 37, 46–62. https://doi.org/10.1016/j.ymben.2016.04.002.
Tokic, M.; Hatzimanikatis, V.; Miskovic, L. Large-Scale Kinetic Metabolic Models of Pseudomonas Putida KT2440 for Consistent Design of Metabolic Engineering Strategies. Biotechnology for Biofuels 2020, 13 (1), 33. https://doi.org/10.1186/s13068-020-1665-7.

**Comment by weilandtd** [comment]
The issue should not persist in the latest release [v1.0.1](https://github.com/EPFL-LCSB/skimpy/releases/tag/v1.0.1)
